name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Fetch Postman Environment
        run: |
          curl -X GET "https://api.getpostman.com/environments/21344086-e7c005e1-0a0a-46f8-8356-37562aeff59a" \
          -H "X-Api-Key: ${{ secrets.POSTMAN_GITHUB_KEY }}" \
          -o environment.json

      - name: Transform Environment File
        run: |
          jq '.environment' environment.json > environment_transformed.json

      - name: Debug - Show contents of environment file
        run: |
          echo "Contents of environment.json:"
          cat environment.json

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Debug - Çalışma Alanındaki Dosyaları Listele
        run: ls -al   

      - name: Run API tests with Newman and generate HTMLExtra report
        run: |
          newman run "${{ github.workspace }}/postman/collections/Restful.json" -e environment_transformed.json --reporters cli,htmlextra --reporter-htmlextra-export "newman-report-restful.html"
          newman run "${{ github.workspace }}/postman/collections/Api Collection.json" -e environment_transformed.json --reporters cli,htmlextra --reporter-htmlextra-export "newman-report-api.html"

      - name: Debug - HTML Raporunun Oluşturulup Oluşturulmadığını Kontrol Et
        run: ls -al

      - name: Upload HTML Reports
        uses: actions/upload-pages-artifact@v3
        with:
          name: newman-reports
          path: |
            newman-report-restful.html
            newman-report-api.html
